### ISSUE TITLE
plotly.plotly issue

### ISSUE THREAD

**Issue by jmillerbrooks** [learn-co-curriculum/rules-for-derivatives-lab#23] opened 2020-04-27 19:38 UTC
The plotly.plotly bit in this lab appears to be outdated, I tried instead:

`!pip install chart-studio`
`import chart_studio.plotly as py`

This appeared to work.

**Comment by jessepisel** [comment] 2022-11-23 20:46
Thanks for opening this @jmillerbrooks :wave:. This is a duplicate of #20. Addressed with 0eeab5746a7073fa034e59f864b8ec00b305fb30 and environment updated [here](https://github.com/learn-co-curriculum/dsc-data-science-env-config/tree/chart_studio_add) I am closing the issue at this time.

**Closed as completed by jessepisel** 2022-11-23 20:46 UTC
