### ISSUE TITLE
Rules for Derivatives Lab Issues

### ISSUE THREAD

**Issue by dv11364** [learn-co-curriculum/rules-for-derivatives-lab#24] opened 2020-05-11 16:39 UTC
1. When giving an overview of `function_values_trace` it fails to mention that you need to import `trace_values` from `graph`. Else, when evaluating the `derivative_function_trace` you'll get an error saying `trace_values` is not defined.

2. When defining returning the output of `trace_values` in `derivative_function_trace` the last argument should be `mode = 'lines'` not `mode = 'lines'`. Else you'll get issues at the end when plotting.

3. When plotting the traces of `derivative_function_trace` side by side, `import plotly.plotly as py` should be `import plotly.offline as py`. Importing `subplots` from `plotly` will help you avoid issues at the end.

**Comment by jessepisel** [comment] 2022-11-23 20:56
Thanks for opening this issue @danvalen1 . I am not able to reproduce issues 1 and 2 at this time. Please see #20 for the resolution to point 3. 

I am closing this issue at this time.

**Closed as completed by jessepisel** 2022-11-23 20:56 UTC
