### ISSUE TITLE
Error at end of lab

### ISSUE THREAD

**Issue by tcmcaleer** [learn-co-curriculum/rules-for-derivatives-lab#30] opened 2020-08-26 00:27 UTC
ImportErrorTraceback (most recent call last)
<ipython-input-24-8af9df3f418b> in <module>
      1 from plotly import tools
      2 import plotly
----> 3 import plotly.plotly as py
      4 
      5 from graph import make_subplots

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/plotly/__init__.py in <module>
      2 from _plotly_future_ import _chart_studio_error
      3 
----> 4 _chart_studio_error("plotly")

/opt/conda/envs/learn-env/lib/python3.6/site-packages/_plotly_future_/__init__.py in _chart_studio_error(submodule)
     47 chart_studio.{submodule} module instead.
     48 """.format(
---> 49             submodule=submodule
     50         )
     51     )

ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead.

**Comment by jessepisel** [comment] 2022-11-23 20:48
Thanks for opening this @tcmcaleer :wave:. This is a duplicate of #20. Addressed with 0eeab5746a7073fa034e59f864b8ec00b305fb30 and environment updated [here](https://github.com/learn-co-curriculum/dsc-data-science-env-config/tree/chart_studio_add) I am closing the issue at this time.

**Closed as completed by jessepisel** 2022-11-23 20:48 UTC
