### ISSUE TITLE
plotly.plotly module is deprecated

### ISSUE THREAD

**Issue by tvvu2020** [learn-co-curriculum/rules-for-derivatives-lab#21] opened 2020-04-04 21:28 UTC
Hello,

I tried to run the code below to import plotly. The code was provided as part of the lab. I got the error message below, "plotly.plotly module is deprecated." Please let me know how I can fix it to complete the lab. Thank you.

from plotly import tools #provided and don't work
import plotly
import plotly.plotly as py

ImportErrorTraceback (most recent call last)
<ipython-input-19-3a2aa877bf9c> in <module>
      1 from plotly import tools #provided and don't work
      2 import plotly
----> 3 import plotly.plotly as py
      4 
      5 #from graph import tools

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/plotly/__init__.py in <module>
      2 from _plotly_future_ import _chart_studio_error
      3 
----> 4 _chart_studio_error("plotly")

/opt/conda/envs/learn-env/lib/python3.6/site-packages/_plotly_future_/__init__.py in _chart_studio_error(submodule)
     47 chart_studio.{submodule} module instead.
     48 """.format(
---> 49             submodule=submodule
     50         )
     51     )

ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead.

**Comment by akaigraham** [comment] 2020-04-08 18:11
I figured out how to fix this

add this line of code
!pip install chart_studio
and then change the line of code that says import plotly.plotly as py to import chart_studio.plotly as py and it should work

**Comment by jessepisel** [comment] 2022-11-23 20:45
Thanks for opening this @tvvu2020 and for the response @akaigraham :wave:. This is a duplicate of #20. Addressed with 0eeab5746a7073fa034e59f864b8ec00b305fb30 and environment updated [here](https://github.com/learn-co-curriculum/dsc-data-science-env-config/tree/chart_studio_add) I am closing the issue at this time.

**Closed as completed by jessepisel** 2022-11-23 20:45 UTC
