### ISSUE TITLE
import errors in example code

### ISSUE THREAD

**Issue by MWilliamson96** [learn-co-curriculum/rules-for-derivatives-lab#25] opened 2020-06-14 23:01 UTC
![image](https://user-images.githubusercontent.com/38963404/84606139-baadb700-ae68-11ea-87f7-14082bcd37a3.png)

error says plotly.plotly module is deprecated, have gotten this message as a warning earlier in the course, this is the first time its caused an error though

**Comment by MWilliamson96** [comment] 2020-06-14 23:03
I tried to change the import statement to use the recommended package (chart_studio.plotly) and got a non-existent module error

**Comment by jessepisel** [comment] 2022-11-23 20:46
Thanks for opening this @MWilliamson96 :wave:. This is a duplicate of #20. Addressed with 0eeab5746a7073fa034e59f864b8ec00b305fb30 and environment updated [here](https://github.com/learn-co-curriculum/dsc-data-science-env-config/tree/chart_studio_add) I am closing the issue at this time.

**Closed as completed by jessepisel** 2022-11-23 20:46 UTC
